### PR TITLE
Add a typo

### PR DESCRIPTION
**Pull request by oznogon**
The transcription for page 1430 includes an apostrophe in "don't" that isn't present in the [scanned source code of that page](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/1430.jpg).

### CODE REVIEW

**Comment by InDieTasten** [comment]
The irony of adding a typo to make it more correct :heart_eyes:

**Comment by oldmud0** [comment]
Science!

**Comment by chrislgarry** [comment]
Awesome! First to fix a typo typo. You have some conflicts. Please git pull the latest. We reorganized the files into directories.

**Comment by oznogon** [comment]
@chrislgarry Rebased!

**Pull request merged**
