### PR TITLE
README translated in Hindi

### PR DESCRIPTION
**Pull request by ramantehlan**
README  has been translated to Hindi, also links to it have been updated.

### CODE REVIEW

**Comment by wopian** [comment]
Thank you 🎉 

Are you able to translate `Part of the source code for Colossus 2A, the Command Module's (CM) Apollo Guidance Computer (AGC) for Apollo 11` and the similar row below it

**Comment by ramantehlan** [comment]
@wopian requested changes have been made. 
CC: @chrislgarry

**Comment by ramantehlan** [comment]
@prashnts your help is welcomed, you can add commits to this pull request, follow the steps given below.

1. Fork [ramantehlan/Apollo-11](https://github.com/ramantehlan/Apollo-11).
2. Branch out to make your improvements.
3. Submit a pull request to `master-hindi`.

Then you commit will also be added here, by default.

**Comment by ramantehlan** [comment]
@prashnts any update on the improvements? 
@wopian requested changes have been made, what is your status on this PR?

**Comment by wopian** [comment]
@ramantehlan I was waiting on prashnts, but I can merge this and improvements/fixes can be done retrospectively in new PRs

**Pull request merged**
