### PR TITLE
Fix typo in Page 1220

### PR DESCRIPTION
**Pull request by kirai**

### CODE REVIEW

**Comment by f00stx** [comment]
Saving the space program one typo at a time.

**Comment by giraam** [comment]
Thanks for your contribution to our planet

**Comment by chrislgarry** [comment]
Need to investigate which typos are in the original source. If this is a typo of the person who digitized, I will merge it in.

**Comment by oznogon** [comment]
This fix is correct. It is `ROUTINE` in the scan of [page 1220](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/1220.jpg).

**Comment by chrislgarry** [comment]
@kirai can you resolve merge conflicts? Thanks.

**Comment by chrislgarry** [comment]
This has been resolved by 91.

**Pull request closed without merging**
