### PR TITLE
Proof LEM_GEOMETRY #604

### PR DESCRIPTION
**Pull request by GintasS**
Not sure about LINE 55 COUNT*

### CODE REVIEW

**Review by wopian — CHANGES_REQUESTED** [review]
The alignment changes to the assembly code is incorrect - how the code was originally aligned is how it should be (see other files for columns). I've reverted this change only as far as page 320. Please revert the Assembly code alignment changes for pages 321-325.

image

**Comment by GintasS** [comment]
> The alignment changes to the assembly code is incorrect - how the code was originally aligned is how it should be (see other files for columns). I've reverted this change only as far as page 320. Please revert the Assembly code alignment changes for pages 321-325.
> 
> image

Fixed formatting.

**Comment by wopian** [comment]
> Fixed formatting.

The indentation between the Assembly code columns need to be with tab characters not spaces

**Review by wopian — APPROVED** [review]

**Comment by wopian** [comment]
Thank you for promptly applying the requested changes 👍

**Pull request merged**
