### PR TITLE
add Turkish README.tr.md

### PR DESCRIPTION
**Pull request by mabdullahsoyturk**

### CODE REVIEW

**Comment by mabdullahsoyturk** [comment]
CONTRIBUTING.tr.md added.

**Comment by mabdullahsoyturk** [comment]
@sariug @wopian Any updates?

**Comment by wopian** [comment]
@mabdullahsoyturk waiting on a response from someone I asked to review it 👍

**Comment by mabdullahsoyturk** [comment]
Conflicts resolved

**Comment by mabdullahsoyturk** [comment]
> @mabdullahsoyturk waiting on a response from someone I asked to review it

still waiting?

**Pull request merged**
