### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Sliqric7053**
Changed "RESTROED" to "RESTORED"

### CODE REVIEW

**Comment by wopian** [comment]
:+1:  [Page 1497](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/1497.jpg)

**Comment by chrislgarry** [comment]
@Sliqric7053 can you resolve the merge conflicts? Thanks.

**Comment by Sliqric7053** [comment]
Hi @chrislgarry I'm pretty much stumped - what's the best way to resolve this merge conflict?

**Comment by chrislgarry** [comment]
@Sliqric7053 in your local copy of this repo just run 'git pull'. It'll prompt to you make a commit, so just do as it says. Then run 'git rebase'. Then you should be able to make the pull request again. Or, if you used the web interface and not the command line, you can just close this and go do the same thing again which will open a new request without the issues.

**Pull request closed without merging**
