### PR TITLE
Typo Fix - TEH to THE

### PR DESCRIPTION
**Pull request by Prabhurajn**

### CODE REVIEW

**Comment by checkplys** [comment]
#77

**Comment by wopian** [comment]
@checkplys that PR was for different files.

All of these are correct, so ready to merge once updated to master.

1 - [Page 0460](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/0460.jpg)
2 and 3 - [Page 0461](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/0461.jpg)
4 - [Page 0775](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/0775.jpg)
5 - [Page 0381](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/0381.jpg)
6 - [Page 1292](http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/1292.jpg)
7 - [Page 1407](http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/1407.jpg)
8 and 9 - [Page 0619](http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/0619.jpg)

**Comment by chrislgarry** [comment]
@Prabhurajn can you resolve the merge conflicts? Thanks.

**Comment by Prabhurajn** [comment]
@chrislgarry Conflicts Resolved. please review and merge

**Comment by chrislgarry** [comment]
@Prabhurajn thanks! @wopian thanks for double checking.

**Comment by GanoNora22** [comment]
Gesendet von meinem Windows Phone
________________________________
Von: Chris Garry
Gesendet: 16.07.2016 16:46
An: chrislgarry/Apollo-11
Betreff: Re: [chrislgarry/Apollo-11] Typo Fix - TEH to THE (#131)


@Prabhurajn<https://github.com/Prabhurajn> thanks! @wopian<https://github.com/wopian> thanks for double checking.

-

**Pull request merged**
