### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Femi123p**
As mentioned in copyright domain, these code belongs to public domain. So ~GNU GPLv3~ "unlicenced" is the best suited license.

### CODE REVIEW

**Comment by wopian** [comment]
The source code is under public domain - [it is not one and the same](http://adamtaylor.info/essays/pd_bsd_gpl.html) as the GPL license.

**Comment by Femi123p** [comment]
@wopian 
Thanks for pointing out I have changed the license to public domain.

**Comment by chrislgarry** [comment]
Guys, lets be careful and do due diligence. virtualagc clearly expresses they are uncertain about the licensing:

```
The software for the Apollo Guidance Computer (AGC) and LM Abort
Guidance Computer (AGS) is believed to be in the public domain.
```

I should've resolved this sooner. I would say that NASA is the authority on the licensing of code developed by NASA for the US government, and therefore lets follow the [NASA Open Source Agreement](https://ti.arc.nasa.gov/opensource/nosa/) for now. By the way, our repo is listed on [NASA's open source website](https://code.nasa.gov), so we need to take care. Lets put up the license I linked to for now. I've contacted some people at NASA and will have an answer soon.

**Comment by oldmud0** [comment]
If the scans were never given to the Virtual AGC team under that open-source agreement, it would be wise to hold off on adding any license at all until you get a definitive answer. Works by government employees are almost always under the public domain, but some works that used to be secret or which had export restrictions might have strings attached (this is more relevant to software currently being used, or recently declassified works). It just depends on what conditions all of those AGC documents were released, when they were released by NASA.

**Comment by chrislgarry** [comment]
Will reach out again soon. No response yet. I asked someone who is likely too busy at the moment. Considering to reach out to legal team directly.

**Comment by wopian** [comment]
@chrislgarry any update? Tempted to close this as we already have the copyright status in the READMEs Attribution and in each source file.

**Comment by chrislgarry** [comment]
No update unfortunately :/ I’m pretty sure we are ok though. If it’s an
issue, someone will surely let us know :)

**Comment by Joseph352** [comment]
m

**Comment by wopian** [comment]
Just a side note and not an update for anything:

https://www.ibiblio.org/apollo/ itself (not the VirtualAGC software) is under the `Creative Commons No Rights Reserved License` (now known as `Creative Commons Zero 1.0 Universal Public Domain Dedication`)

> The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law.
>
> You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission.

https://creativecommons.org/publicdomain/zero/1.0/
https://choosealicense.com/licenses/cc0-1.0/

**Comment by wopian** [comment]
The scans for Comanche55 and Luminary99 are under [Public Domain Mark 1.0](https://creativecommons.org/publicdomain/mark/1.0/):

https://archive.org/details/Comanche55J2k60/page/n6/mode/2up
https://archive.org/details/Luminary99001J2k60/page/n16/mode/2up

# Public Domain Mark 1.0
## No Copyright

This work has been identified as being free of known restrictions under copyright law, including all related and neighbouring rights.

You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. See Other Information below.

## Other Information

* The work may not be free of known copyright restrictions in all jurisdictions.
* Persons may have other rights in or related to the work, such as patent or trademark rights, and others may have rights in how the work is  used, such as publicity or privacy rights.
* In some jurisdictions moral rights of the author may persist beyond the term of copyright. These rights may include the right to be identified as the author and the right to object to derogatory treatments.
* Unless expressly stated otherwise, the person who identified the work makes no warranties about the work, and disclaims liability for all uses of the work, to the fullest extent permitted by applicable law.
* When using or citing the work, you should not imply endorsement by the author or the person who identified the work.

**Pull request closed without merging**
