### PR TITLE
Fix typo in AGC_BLOCK_TWO_SELF_CHECK.s

### PR DESCRIPTION
**Pull request by stefkin**

### CODE REVIEW

**Comment by chrislgarry** [comment]
Need to investigate which typos are in the original source. If this is a typo of the person who digitized, I will merge it in.

**Comment by oznogon** [comment]
This fix is correct. It is `WITH` in the scan of [page 1285](http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/1285.jpg).

**Comment by chrislgarry** [comment]
@stefkin could you resolve merge conflicts? Thanks.

**Comment by stefkin** [comment]
done

**Pull request merged**
