### PR TITLE
Create MATTDAMON.s

### PR DESCRIPTION
**Pull request by nuuman**
Routine for picking up Matt Damon

### CODE REVIEW

**Comment by nuuman** [comment]
This solves https://github.com/chrislgarry/Apollo-11/issues/53

**Comment by KluVerKamp** [comment]
👍

**Comment by robertmain** [comment]
That's all very well, but what if I want to rescue other people like major Major Tom?

**Comment by nuuman** [comment]
My understanding is that Major Tom took his pills and can wait.

**Comment by JonHoye** [comment]
I'm no expert, but after a quick code review, there's some concern. It seems you may have a miscalculation on your initial thrust timing for the Hohmann transfer to return to earth's orbit.

Otherwise, this looks great!

**Comment by nuuman** [comment]
@JonHoye good theory, but you forgot to take the potato payload into account. Matt needs to eat on the way home.

**Comment by knowledgewarrior** [comment]
@nuuman Oxygen level calculations seem a bit low.  How long can Matt Damon hold his breath?

**Comment by chrislgarry** [comment]
See issue [53](https://github.com/chrislgarry/Apollo-11/issues/53). We do not want to pick up Matt Damon.

**Comment by deanlee** [comment]
LOL

**Comment by chenxi91999** [comment]
hahah

**Comment by monkey19911021** [comment]
oh my god...

**Comment by SuddenKey** [comment]
I want to know, 50 years later, people will see ours how to think

**Comment by CosmicYogi** [comment]
lol

**Comment by 972389149** [comment]
RESTART_TABLES.agc 第305行出错了，应该把-2改为-3，不然推力不足

**Pull request closed without merging**
