### PR TITLE
This seems to be a typo.

### PR DESCRIPTION
**Pull request by felipesanches**
Please check if that's the case :-)

### CODE REVIEW

**Comment by ryanjadhav** [comment]
+1

**Comment by vagnerbezerraf** [comment]
tks!
Em 10/07/2016 23:14, "Ryan Jadhav" <notifications@github.com> escreveu:

**Comment by oznogon** [comment]
Confirmed on the scan of [page 806](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/0806.jpg).

**Comment by chrislgarry** [comment]
Please resolve merge conflicts.

**Comment by felipesanches** [comment]
done

**Comment by chrislgarry** [comment]
@felipesanches thanks. @oznogon thanks for checking.

**Pull request merged**
