### PR TITLE
Added Comment on PIINVERS

### PR DESCRIPTION
**Pull request by jseger**

### CODE REVIEW

**Comment by oldmud0** [comment]
The project is only accepting preserved/historical content, sorry.

**Comment by jseger** [comment]
No problem!!!  That's what I figured afterwards.  Thanks!

**Comment by chrislgarry** [comment]
@jseger there are plenty of other ways to contribute though! Check out the README for how to contribute. We have the original scans of the source, and there are typos/comments to correct.

**Comment by chrislgarry** [comment]
@oldmud0 thanks.

**Pull request closed without merging**
