### PR TITLE
Update AGS_INITIALIZATION.s

### PR DESCRIPTION
**Pull request by guilhermeblanco**
Missing required space between instruction and comment could break compilation.

### CODE REVIEW

**Comment by chrislgarry** [comment]
Good catch!

**Comment by mausworks** [comment]
Did you just make an actual update to Apollo 11's source code? 
Was it "original" before the update, or is it now? :confused:

**Comment by chrislgarry** [comment]
The original source was digitized and some comments were added. This change
fixed one of those added comments.

**Comment by onmyway133** [comment]
@guilhermeblanco what do you use to compile this?

**Pull request merged**
