### PR TITLE
Proof RESTART_TABLES #633

### PR DESCRIPTION
**Pull request by RichardPilbery**

### CODE REVIEW

**Comment by wopian** [comment]
Reminder for review - answer question asked in https://github.com/chrislgarry/Apollo-11/issues/633#issuecomment-703770649

**Comment by wopian** [comment]
> Okay I've made a start with this but need some advice about the tables themselves. Page 239 has a number of columns that precede the columns included in RESTART_TABLES.agc.
[>](url)
> For example, line A0079 on page 239 is:
>
> REF 29 LAST 213. 0074. then a couple of columns then EBANK- STATE
>
> Should these be included?

These shouldn't be included. The columns of data on the left of the Assembly code is compiler info/output that we don't record in this repository.

**Comment by RichardPilbery** [comment]
Brilliant, in which case this PR should be good to go.

**Review by wopian — APPROVED** [review]

**Comment by wopian** [comment]
Thank you for the PR 👍

**Comment by RichardPilbery** [comment]
No worries, I'll definitely try to submit more!

**Pull request merged**
