### PR TITLE
Reassign AGC file extension to assembly files

### PR DESCRIPTION
**Pull request by Alhadis**
Since things are looking [pretty square](https://github.com/github/linguist/pull/3112) at Linguist (minus Travis's colour-blindness), I figure I'd rename the files back to `.agc` for you in advance. =)

Dunno if this actually helps, or if I'm just getting underfoot.

### CODE REVIEW

**Comment by chrislgarry** [comment]
@Alhadis LGTM. Waiting for the merge. Is it continuous deployment, or do we have to wait a bit for the changes to take affect? I want to merge this when there is no interruption to syntax highlighting.

**Comment by Alhadis** [comment]
Basically, changes to Linguist take effect once a new release is cut. Arfon said he'll do so shortly after the PR is merged.

You can go ahead and [delete Markdown's colour](https://github.com/github/linguist/pull/3113), BTW. =) That'll get your PR in the clear and we can get that merged.

**Comment by Alhadis** [comment]
Conflicts fixed. =)

You might wanna squash these commits so we're not left looking at a morass of `Merge branch 'master' into rename` in the revision history, heh.

**Comment by Alhadis** [comment]
Okay, Linguist v4.8.8 is released! :D It's safe to merge now!

**Comment by arfon** [comment]
:boom: 🚀

**Comment by chrislgarry** [comment]
@Alhadis thanks for the fabulous grammars @arfon thanks for cutting a new gem so quickly

**Comment by arfon** [comment]
@chrislgarry these *are* now being correctly classified as `Apollo Guidance Computer` but the fact that they're in [the `Assembly` group](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L194) means that the repo language bar shows `Assembly`

**Comment by 24s92tntks-oss** [comment]
.gitmodules

**Pull request merged**
