### PR TITLE
Refine zh_tw translation

### PR DESCRIPTION
**Pull request by yyc1217**

### CODE REVIEW

**Comment by JerryChin** [comment]
> 如果因為某些原因需要合法使用到這些影像，請通過電子郵件 info@sandroid.org 聯繫我，以獲得這些高清影像的使用權。

Are you 100% sure that you're not mistaken?
the counterpart in the original English README.md says:
> If for some reason you find that the images are
 illegible.

**illegible** has nothing to do with **copyright**, do you agree with me?

The work which you're based on contains too many errors, I've issued a new PR #182, can you help to review and translate it to traditional Chinese?

**Comment by yyc1217** [comment]
@JerryChin 
Thanks for pointing me out the error, I changed my translation. Please let me know if you find any others.
I already translated to Traditional Chinese.

**Comment by wopian** [comment]
@yyc1217 & @JerryChin, is this ok to be merged or are there changes still required?

**Comment by yyc1217** [comment]
@wopian I've corrected my translations according to @JerryChin's comment. I think it's ok to be merged now unless @JerryChin can tell us what are the other errors.

**Comment by JerryChin** [comment]
I agree to merge these changes.

**Pull request merged**
