### PR TITLE
Fixed typo in master ignition routine.

### PR DESCRIPTION
**Pull request by JackieChiles**

### CODE REVIEW

**Comment by chrislgarry** [comment]
Need to investigate which typos are in the original source. If this is a typo of the person who digitized, I will merge it in.

**Comment by CodeTheory** [comment]
This looks to be an original mistake: http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/0731.jpg (line 0013)

**Comment by chrislgarry** [comment]
@CodeTheory thanks!

**Comment by akostadinov** [comment]
I guess project needs to be forked under FSF so errors are removed and diy lunar expeditions become safer..

**Pull request closed without merging**
