### PR TITLE
hi

### PR DESCRIPTION
**Pull request by ter0x1a**

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
what

**Comment by CrazyPython** [comment]
That's a bad PR name.

**Comment by nabijaczleweli** [comment]
and a terrible "PR" in and of itself

**Comment by nabijaczleweli** [comment]
I betcha it's one of those "first PR" thingies that are 100% worthless and just waste everybody's time

**Comment by oldmud0** [comment]
Hello

**Comment by CrazyPython** [comment]
@ter0x1a Test on https://github.com/octocat/Spoon-Knife.

**Pull request closed without merging**
