### PR TITLE
PROOF R60_62 ISSUE #

### PR DESCRIPTION
**Pull request by WCoder007**
Complete proofreading done for R60_62 Issue #628

### CODE REVIEW

**Comment by WCoder007** [comment]
@wopian If you are satisfied with the PR, please dont forget to add the hacktoberfest accepted label, thank you :)

**Comment by wopian** [comment]
@WCoder007 I'm going in order of date opened (currently 12th in line of 21) 👍

**Comment by wopian** [comment]
I've added the `hacktoberfest-accepted` label to ensure your contribution counts towards Hacktoberfest, as I haven't been able to review as many PRs as I had hoped over the past few days in my free time.

I'm currently working through this one and should be fully reviewed soon.

**Review by wopian — APPROVED** [review]

**Comment by wopian** [comment]
Thank you for contributing 👍 

I've corrected some of the commas that were mistakenly changed to full stops and a few others I spotted while reviewing the file. 

Apologies for the significant delay in reviewing - I had other things come up and then had to deal with a hardware failure 😢

**Pull request merged**
