### PR TITLE
Page 1 is in Luminary099/CONTRACT_AND_APPROVALS.agc

### PR DESCRIPTION
**Pull request by proudindiv**

### CODE REVIEW

**Comment by oldmud0** [comment]
I'm going to hold off on this. It might be better to do it the other way around (i.e. remove `CONTRACT_AND_APPROVALS.agc`) because there is apparently neither a reference to a contract nor approvals in the file.

**Comment by proudindiv** [comment]
Yes, fine.

**Comment by wopian** [comment]
Removing the CONTRACT file and leaving the code in here should be the way forward, as the title of [Page 0001](http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/0001.jpg) is "Assembly and Operation Information" on both.

**Comment by oldmud0** [comment]
All right, I shall do that now.

**Pull request closed without merging**
