### PR TITLE
Add CONTRIBUTING + EditorConfig

### PR DESCRIPTION
**Pull request by wopian**
This adds a CONTRIBUTING file which will appear above every new pull request.

It provides some rough guidelines on what to check for in the code, including the outcome of #159 about line breaks.

Additionally it also adds a [EditorConfig](http://editorconfig.org/#file-format-details) file to the root, so editing files directly on GitHub will enforce the recommended settings for AGC Assembly.

### CODE REVIEW

**Comment by chrislgarry** [comment]
Thanks @wopian. Having a look.

**Comment by chrislgarry** [comment]
That bored someone was me :) It wasn't much work actually since I based it
on regular assembly syntax highlighting.

**Comment by wopian** [comment]
@chrislgarry 👍❔

**Comment by chrislgarry** [comment]
LGTM

**Pull request merged**
