### PR TITLE
Fix typo in a comment in LEM_GEOMETRY.s

### PR DESCRIPTION
**Pull request by marwanh**
Replaced APPROPIRATELY with APPROPRIATELY.
No wonder they didn't find aliens there!

### CODE REVIEW

**Comment by marwanh** [comment]
Typo is not present in the scanned document
[Page 320](http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/0320.jpg)

**Comment by axd1967** [comment]
even if there were a typo, is it OK to correct such typos?

**Comment by chrislgarry** [comment]
@axd1967 these typos are from digitization. It's ok. The goal of this repo is to reflect the primary Apollo 11 source code.

**Comment by chrislgarry** [comment]
@marwanh thanks.

**Pull request merged**
