### PR TITLE
Proof POWERED_FLIGHT_SUBROUTINES #624

### PR DESCRIPTION
**Pull request by serialhex**
Proofread all comments and code.  There are a few comments relating to white space.

1. I used the white space conventions listed in CONTRIBUTING.md, namely:
  * Single space for new words.
  * Double space for new sentences.
  * Triple space for indentations.

I call this out specifically because the scans (at least for this file) seem to use 4 spaces for indentation and 3 spaces for new sentences.  For example, in the following image the leading `C` in `CDUTRIG` would be over the `I` in `COSINES` if it used 3 spaces instead of 4, but instead it is over the `E`.  Similarly, on the 4th line (there's and example on the 3rd but it's easier to see on the 4th) the period at the end of the line corresponds to a space above it, and then there are 3 spaces before the `T` in `THESE` starts.

Scan page 1259

2. Some of the code seem to use spaces and tabs instead of just tabs.  I mentioned it in the issue here: https://github.com/chrislgarry/Apollo-11/issues/624#issuecomment-707207774 so I won't repeat myself.

Other than that this PR should be bug-compatible with the scans! :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by wopian** [comment]
> I used the white space conventions listed in CONTRIBUTING.md, namely:

This was recently updated due to the wording being incorrect (well unhelpful and somewhat contradictory) - it's the general usage of spaces, but whatever the scans uses is what you use.

**Comment by chrislgarry** [comment]
Looks good to me. Thanks!

**Comment by chrislgarry** [comment]
> Good morning @wopian & @chrislgarry!
> 
> If @wopian 's comment is the way it should be, then my contributions are wrong, but easily fixed and it's only white space. If you like I can fix it and open another pull request. Though if that is the case I think that should be updated in the CONTRIBUTING.md file so it is clear that we want white space to match also. I'm happy to do this if it is desired, especially since I'm going to be doing more of these in the next week or so and I want them to be _right_.
> 
> p.s. it's really fun reading these comments, I'm not super much for editing or proofreading in general, it's nice to read code from exceptional engineers!

@wopian has the final word. I may have missed the whitespace nuances since I was reviewing on my phone during my commute home. Regardless, we would be happy if you could submit a new PR accordingly.

**Comment by wopian** [comment]
@serialhex I've reverted this PR. Unfortunately GitHub permanently closes PRs once they're merged so you'll need to create a new branch off of this branch and open a new PR with that.

```git
git checkout POWERED_FLIGHT_SUBROUTINES-proofread
git checkout -b POWERED_FLIGHT_SUBROUTINES-proofread2
git push
(create PR from POWERED_FLIGHT_SUBROUTINES-proofread2)
```

**Pull request merged**
