### PR TITLE
Fix typo in FUNCT. DESCR.

### PR DESCRIPTION
**Pull request by jonathanbruder**

### CODE REVIEW

**Comment by yeukhon** [comment]
@jonathanbruder  you are the first to find a typo. I have been looking for hours.

**Comment by chrislgarry** [comment]
The problem is if it is an original typo or a typo of the person who digitized. I do not want to correct original typos. Let me get my hands on the scanned copies and find out.

**Comment by Austinthemighty** [comment]
@chrislgarry where are the scanned copies

**Comment by dacap** [comment]
@Austinthemighty it looks like the program is here http://www.ibiblio.org/apollo/listings/Luminary099/UPDATE_PROGRAM.agc.html and scanned pages are here: http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/

(From: http://www.ibiblio.org/apollo/links.html)

**Comment by dacap** [comment]
From the [original scan](http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/1386.jpg), it looks like this fix is correct.

**Comment by chrislgarry** [comment]
@dacap thanks for looking into it. will merge in.

**Comment by dacap** [comment]
@chrislgarry you're welcome, finally [the original scanned document is this](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/1497.jpg) (from Comanche055), the fix still is valid.

**Comment by jonathanbruder** [comment]
Thanks, all, for your responsible stewardship.

**Pull request merged**
