### PR TITLE
missing Luminary099 files retrieved from virtualagc at https://github…

### PR DESCRIPTION
**Pull request by proudindiv**
Here are the 51 missing Luminary099 files retrieved from virtualagc at https://github.com/rburkey2005/virtualagc/tree/master/Luminary099 and simply checked against scans at http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/ to verify that they belong.

The only problem that I spotted was some sort of transcription error with Pages 299 and 300 in EXTENDED_VERBS.agc.  I felt it was most important to add the files to the repository first, so that corrections will be in the git logs.  I have not yet done any detailed examination for errors in these original virtualagc files.  If you have problems seeing the files in the pull request because of the size, they are also in my upstream branch at https://github.com/proudindiv/Apollo-11/tree/upstream .

Gary Young
aka proudindiv

### CODE REVIEW

**Comment by wopian** [comment]
Yeah, looks like the people who digitalised that file mislabeled the last 2 pages: pages 300 and 301 instead of 299 and 300.

**Comment by proudindiv** [comment]
Did you notice Comanche055.binsource and Luminary099.binsource in the rburkey2005/virtualagc repo?  I'm thinking of running their assembler on the sources and comparing, or writing my own simple assembler.  Do you think we should bring those files into chrislgarry/Apollo-11?

**Comment by wopian** [comment]
I would disagree with adding those files.

This repo is a historical archive of the Apollo 11 source code, VirtualAGC was made to compile the Apollo 11 code (and will be pulling the .agc files from here once they've all been checked)

Scroll down on #38

**Comment by proudindiv** [comment]
But with that argument, the historical Apollo 11 source code is defined by the jpg images linked to in the chrislgarry/master README.md file.  The added 51 files from the VirtualAGC are required if you are going to match the images.  They are also required if you are going to compile the source code and fly the Apollo-11 to the moon.  There are issues with the encoding used in the VirtualAGC transcriptions representing the original source code, but adding the 51 files doesn't change that issue.

**Comment by chrislgarry** [comment]
@wopian yep that's my stance as well. @proudindiv yes I did plan on doing something with main.agc since its purpose is to be a wrapper to organize all of the assembly files for compliation, but it slipped my mind. We could simply just remove it if there is no original logic in there. I haven't looked yet. I also agree with splitting into the original number of files so we don't have multiple original assembly files in one digital assembly file here. And removal of header template if it's not original.

**Pull request merged**
