### PR TITLE
Typos pp. 1309-37. IMU_MODE_SWITCHING_ROUTINES.agc

### PR DESCRIPTION
**Pull request by mgnoonan**
Matched up the comment formatting with the scans. Also found a couple of labels that were incorrectly transcribed with zeros instead of capital O.

### CODE REVIEW

**Comment by oldmud0** [comment]
Was there a merge conflict?

**Comment by mgnoonan** [comment]
No, I don't think so. Why?

Get Outlook for iOS




On Sun, Aug 21, 2016 at 8:28 PM -0400, "oldmud0" <notifications@github.com> wrote:





Was there a merge conflict?

**Comment by oldmud0** [comment]
Are any of the changes made at commit 9c401b39583c2f0c39f7a495cfb7b3f160778032 yours?

**Comment by mgnoonan** [comment]
Yes, looks like from my first PR. Not sure why it would include those, I thought it was updating from the chrislgarry/master branch. Weird.

 

What would you like me to do?

 

--Matt

**Comment by oldmud0** [comment]
Don't worry, I've taken care of it and merged manually.

**Pull request closed without merging**
