### PR TITLE
fixed Massachusetts typo

### PR DESCRIPTION
**Pull request by cheapwebmonkey**

### CODE REVIEW

**Comment by oznogon** [comment]
This typo appears in most files: https://github.com/chrislgarry/Apollo-11/search?utf8=%E2%9C%93&q=Massachussets

**Comment by cheapwebmonkey** [comment]
Fixed them all

**Comment by wopian** [comment]
The typo is present in the original source, so this PR should be closed.

[Luminary Page 1](http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/0001.jpg)

**Comment by oznogon** [comment]
@wopian I can't see the typo in the source scan. Lines R0004 and R0005 both read `MASSACHUSETTS`, not `MASSACHUSSETS `.

screen shot 2016-07-11 at 2 35 51 pm

Beyond that, Luminary page 1 is transcribed in [CONTRACT_AND_APPROVALS](https://github.com/open-space-agency/virtualagc/blob/master/Luminary099/CONTRACT_AND_APPROVALS.agc). The headings on these files are independent of page 1's transcription.

**Comment by wopian** [comment]
@oznogon yeah, I had a dumb moment and switched red and green around in my head. 

Wasn't until I came back and saw what I had said and what the PR changed that I realised how stupid of a mistake I made :cry:

**Comment by oznogon** [comment]
@wopian No worries! I've gone cross-eyed looking at the scans too. I feel ya.

**Comment by cheapwebmonkey** [comment]
@chrislgarry git pulled and git rebased

**Comment by chrislgarry** [comment]
@cheapwebmonkey thanks!!

**Comment by oldmud0** [comment]
Whoa, this seems to have messed with the history big time. This should have been a clean rebase but it wasn't.

**Pull request merged**
