### PR TITLE
Improved french translation of the contributing file

### PR DESCRIPTION
**Pull request by Aur36**

### CODE REVIEW

**Comment by Aur36** [comment]
Hello, could you please add the label "hacktoberfest-accepted" to this PR ? Many thanks !

**Comment by wopian** [comment]
It shouldn't need the label as it was merged

**Comment by Aur36** [comment]
It is strange because the hacktoberfest website says "Pull request not yet accepted" about this commit, so I wondered if the label could unlock the situation

**Comment by wopian** [comment]
Unfortunately [PRs needed to be merged or accepted (review/label) before 1st November](https://www.digitalocean.com/community/questions/hacktoberfest-my-merged-commit-is-shown-as-not-yet-accepted), which this wasn't (Seen, checked and merged on the 1st at 11am)

**Comment by Aur36** [comment]
That would explain, thank you for the explanation.

**Pull request merged**
