### PR TITLE
Contributing: Add more text editors with AGC syntax support

### PR DESCRIPTION
**Pull request by wopian**
Added some more syntax-only extensions for other popular code editors.

- [x] Arabic
- [x] English
- [x] Korean
- [x] Portuguese
- [x] Turkish

### CODE REVIEW

**Comment by wopian** [comment]
@ardabbour, @0x00000FF, @Gaboso and @mabdullahsoyturk, how would you translate "supports automatic formatting" to the respective languages you translated for?

**Comment by mabdullahsoyturk** [comment]
You can translate it as "otomatik biçimlendirmeyi destekliyor" to Turkish.

**Comment by ardabbour** [comment]
It can be translated as "يدعم التنسيق الآلي" in Arabic.

**Comment by 0x00000FF** [comment]
You can translate them as "자동 포매팅 지원" or "자동 포매팅을 지원합니다."

Former one is phrase, latter one is a sentence.

**Comment by wopian** [comment]
I somehow missed out simplified and traditional Chinese when doing this PR (added in https://github.com/chrislgarry/Apollo-11/commit/82431b26f21d35c9f2ceb24d46cd11d1c9214b3a). 

@walkermanx and @iigmir can you translate "supports automatic formatting"?

**Comment by iigmir** [comment]
OK, I will have a look first.

**Comment by iigmir** [comment]
Hi @wopian, have a look at d62e832 in #655. Thank you.

**Pull request merged**
