### PR TITLE
Fixed Typo in PINBALL_GAME_BUTTONS_AND_LIGHTS.s

### PR DESCRIPTION
**Pull request by kaceyb**
Typo correction line 139.

### CODE REVIEW

**Comment by chrislgarry** [comment]
Can you link to a scan of the original source that indicates this typo was introduced during the digitization? See README for a link to scans. Thanks.

**Comment by RexRowan** [comment]
No, it was an existing error.
screenshot - 7_10_2016 9_27_23 pm

**Comment by oznogon** [comment]
I disagree. The scan of [page 309](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/0309.jpg) on ibiblio clearly show "page numbers". The ibiblio transcription is wrong.

**Comment by jean** [comment]
@oznogon you might want to remove your :+1: reaction above ;-) I agree, the scan shows a "G".

**Comment by RexRowan** [comment]
@oznogon I'm sorry, I went to README and clicked on the links provided and thought they were the original scans. Can you show me a link that link to the scans? Thanks!

**Comment by jean** [comment]
@oznogon already linked to the page in his reply above, it is
http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/0309.jpg

On 11 Jul 2016 5:17 pm, "Tingting Zhao" <notifications@github.com> wrote:
>
> @oznogon I'm sorry, I went to README and clicked on the links provided
and thought they were the original scans. Can you show me a link that link
to the scans? Thanks!

**Comment by RexRowan** [comment]
@jean I see the direct link to the scan and the page for all scans for conversion. I then clicked on the parent directory and wanted to back track the hyperlink on the Home Page links to it, can you tell me where to look? Thanks!

**Comment by RexRowan** [comment]
Ok, I'm too stupid to participate. Thank you for the opportunity and patience.

**Comment by jean** [comment]
Ah, now I understand what you're looking for. I think this is what you're
looking for: http://www.ibiblio.org/apollo/links.html

Sorry I was slow to understand.
On 11 Jul 2016 5:46 pm, "Tingting Zhao" <notifications@github.com> wrote:

Ok, I'm too stupid to participate. Thank you for the opportunity and
patience.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/chrislgarry/Apollo-11/pull/58#issuecomment-231701658>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAFLQPtNvSEGgGse63brZvETbfH6Jovfks5qUh74gaJpZM4JI2uL>
.

**Comment by RexRowan** [comment]
@jean I am very sorry that I didn't explain very clearly. I didn't think the two links on the [README ](https://github.com/chrislgarry/Apollo-11)section is of much help for people who want to find the original scans because they appear to be transcripts already.

I wanted to find the route of how @oznogon found his link to the images from the home page. Now I have found it: go to [(http://www.ibiblio.org/apollo/,)] then click Colossus on the right side of the menu in the nav section, then scroll down the table until Applo 11 mission, in the 5th colume named 'source code', there are two hyperlinks, one as colorized, hyperlinked,  HTML and the other as scanned page images (very big!), the second link leads to the original scans and the numbers of the images seems to corresponde to the pages numbers.

The other route is the Luminary link in the nav section but the contents seem to be different. :smiley:

**Comment by chrislgarry** [comment]
@RexRowan sorry about that. I updated the links in the README to point to the original scans. @kaceyb can you resolve merge conflicts? Thanks.

**Comment by kaceyb** [comment]
@chrislgarry I would be glad to. I am still learning Git, so just don't let me waste your time if I am doing something wrong. I appreciate the opportunity!

**Comment by kaceyb** [comment]
@chrislgarry I am not sure I have done this correctly, but I have created a new pull request that shows that is can be merged. I am closing this original pull request as it is now a duplicate. I have tried covering my bases and researching how to do this. Apologies if this is incorrect. Thanks!

**Comment by RexRowan** [comment]
@kaceyb I think you need to have the authorization to merge it.

**Comment by kaceyb** [comment]
@rexrowan Ah, that clears up a few things! Thanks!

**Pull request closed without merging**
