### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by cherurg**
✌

### CODE REVIEW

**Comment by chrislgarry** [comment]
Need to investigate which typos are in the original source. If this is a typo of the person who digitized, I will merge it in.

**Comment by cherurg** [comment]
@chrislgarry ok, thanks!

**Comment by dakhota** [comment]
ANYJOB seems to be an identifier; see two lines above change.

**Comment by dakhota** [comment]
ANYJOB seems to be an identifier of some sort; see two lines above change.

**Comment by oznogon** [comment]
It is `ANYJOB` in the scan of [page 211](http://www.ibiblio.org/apollo/ScansForConversion/Comanche055/0211.jpg).

**Comment by chrislgarry** [comment]
Typo is original.

**Pull request closed without merging**
