### PR TITLE
Fix AGS INITIALIZATION typo.

### PR DESCRIPTION
**Pull request by oznogon**

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
*well, technically, strimmer, it should actually be "INITIALISATION"*

**Comment by chrislgarry** [comment]
I need to find out if this is an original typo, or a typo of the person who digitized. If it is original, we want to keep it.

**Comment by CodeTheory** [comment]
Looks to be a good if this is the original scan http://www.ibiblio.org/apollo/ScansForConversion/Luminary099/0206.jpg

**Comment by chrislgarry** [comment]
Thanks all. Merged.

**Pull request merged**
