### PR TITLE
cleanup Lunar Landing Guidance Equations

### PR DESCRIPTION
**Pull request by pellyg**
I saw some old code that should have been removed a while ago, so I cleaned it up.

### CODE REVIEW

**Comment by openfly** [comment]
bahahaha

**Comment by thunderrabbit** [comment]
hahahah nice find.

**Comment by s-chizhik** [comment]
I guess you should also provide some tests.

**Comment by vipslord** [comment]
👍

**Comment by gcoon151** [comment]
I think @pellyg should send another Apollo LM-5 to an equivalent site to make sure there isn't an undocumented dependency. 

This github project is awesome on many levels.

**Comment by chrislgarry** [comment]
This may well be a historical instance of technical debt that paid off.

**Pull request closed without merging**
